### ISSUE TITLE
Personal content impersonal style

### ISSUE THREAD

**Issue by tzohpilotl** [UlisesAC4/firstAssignment#6]
Hi, Ulises, it's funny that one can tell immediatly that you used materialize, like me. I loved the colors you chose for your page, very relaxing ones, they go very well together. Is fantastic that you took the time to share your interests in such detail with us, I appreciate that. You could improve your desing putting on more colors because right now your page looks a little like a template of a framework, that would inject the same personality you put in your text into your design. Have a nice day!

**Comment by ulisesac4** [comment]
Ohh thank you, I know materialize rocks!, and well I would not know how I could change the colors to resemble my personality, actually I have uploaded the project with a better design trying to improve the project according with all the suggestions :)
