### ISSUE TITLE
Nav-bar

### ISSUE THREAD

**Issue by salvadorJimenez** [UlisesAC4/firstAssignment#7]
I have to tell you that it's a great page, and you have a really interesting personality, i feel like we can be friends. So i'm just have one thing to say, so here we go.

The nav bar doesn't work in the phone, the elements is over the others and is not understandable so  you can't use the nav bar properly. 

So see you around and good job. :D

**Comment by ulisesac4** [comment]
If you say so then we can be friends :), after all we are working in the same project.

The navbar is already fixed, took a bit longer than expected, but trust me is better now :)
